import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  images: {
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 31536000,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: 'plus.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: 'vernonskinclinic.com',
      },
      {
        protocol: 'https',
        hostname: 'img.youtube.com',
      },
    ],
  },
  async redirects() {
    return [
      // ===== WordPress Legacy URL Redirects (from crawl) =====
      // Hair Transplant pages
      { source: '/hair-transplantation', destination: '/treatments/hair-restoration/hair-transplant', permanent: true },
      { source: '/hair-transplantation/', destination: '/treatments/hair-restoration/hair-transplant', permanent: true },
      { source: '/what-is-a-dhi-technique', destination: '/treatments/hair-restoration/dhi-hair-transplant', permanent: true },
      { source: '/what-is-a-dhi-technique/', destination: '/treatments/hair-restoration/dhi-hair-transplant', permanent: true },
      { source: '/fut-fue-combined-hair-transplant', destination: '/treatments/hair-restoration/hair-transplant', permanent: true },
      { source: '/fut-fue-combined-hair-transplant/', destination: '/treatments/hair-restoration/hair-transplant', permanent: true },
      { source: '/fuefutbht-combine-technique-for-hair-transplant', destination: '/treatments/hair-restoration/body-hair-transplant', permanent: true },
      { source: '/fuefutbht-combine-technique-for-hair-transplant/', destination: '/treatments/hair-restoration/body-hair-transplant', permanent: true },
      { source: '/body-hair-transplant', destination: '/treatments/hair-restoration/body-hair-transplant', permanent: true },
      { source: '/body-hair-transplant/', destination: '/treatments/hair-restoration/body-hair-transplant', permanent: true },
      { source: '/eyebrow-hair-transplant', destination: '/treatments/hair-restoration/beard-eyebrow-restoration', permanent: true },
      { source: '/eyebrow-hair-transplant/', destination: '/treatments/hair-restoration/beard-eyebrow-restoration', permanent: true },
      { source: '/women-hair-transplant', destination: '/treatments/hair-restoration/women-hair-transplant', permanent: true },
      { source: '/women-hair-transplant/', destination: '/treatments/hair-restoration/women-hair-transplant', permanent: true },
      { source: '/information-about-hair-transplant', destination: '/treatments/hair-restoration/hair-transplant', permanent: true },
      { source: '/information-about-hair-transplant/', destination: '/treatments/hair-restoration/hair-transplant', permanent: true },

      // Hair Treatment pages
      { source: '/gfc-hair-treatment-benefits-for-hair-loss', destination: '/treatments/hair-restoration/prp-gfc-therapy', permanent: true },
      { source: '/gfc-hair-treatment-benefits-for-hair-loss/', destination: '/treatments/hair-restoration/prp-gfc-therapy', permanent: true },
      { source: '/revitalized-hair-with-gfc-hair-treatment', destination: '/treatments/hair-restoration/prp-gfc-therapy', permanent: true },
      { source: '/revitalized-hair-with-gfc-hair-treatment/', destination: '/treatments/hair-restoration/prp-gfc-therapy', permanent: true },
      { source: '/advanced-bio-hair-therapy-with-gfc-hair-treatment-2', destination: '/treatments/hair-restoration/prp-gfc-therapy', permanent: true },
      { source: '/advanced-bio-hair-therapy-with-gfc-hair-treatment-2/', destination: '/treatments/hair-restoration/prp-gfc-therapy', permanent: true },
      { source: '/meso-therapy-hair', destination: '/treatments/hair-restoration/mesotherapy-hair', permanent: true },
      { source: '/meso-therapy-hair/', destination: '/treatments/hair-restoration/mesotherapy-hair', permanent: true },
      { source: '/laser-for-hair-growthlllt', destination: '/treatments/hair-restoration/prp-gfc-therapy', permanent: true },
      { source: '/laser-for-hair-growthlllt/', destination: '/treatments/hair-restoration/prp-gfc-therapy', permanent: true },

      // Skin Treatment pages
      { source: '/derma-peels-skin-treatment', destination: '/treatments/aesthetics/derma-peels', permanent: true },
      { source: '/derma-peels-skin-treatment/', destination: '/treatments/aesthetics/derma-peels', permanent: true },
      { source: '/vernon-laser-treatment', destination: '/treatments/laser-and-pico/pico-laser-pigmentation', permanent: true },
      { source: '/vernon-laser-treatment/', destination: '/treatments/laser-and-pico/pico-laser-pigmentation', permanent: true },
      { source: '/unlock-clear-radiant-skin-with-q-switched-laser-treatment', destination: '/treatments/laser-and-pico/q-switched-laser', permanent: true },
      { source: '/unlock-clear-radiant-skin-with-q-switched-laser-treatment/', destination: '/treatments/laser-and-pico/q-switched-laser', permanent: true },
      { source: '/top-skin-brightening-treatments', destination: '/treatments/laser-and-pico/pico-laser-pigmentation', permanent: true },
      { source: '/top-skin-brightening-treatments/', destination: '/treatments/laser-and-pico/pico-laser-pigmentation', permanent: true },
      { source: '/botox-and-fillers', destination: '/treatments/aesthetics/botox-fillers', permanent: true },
      { source: '/botox-and-fillers/', destination: '/treatments/aesthetics/botox-fillers', permanent: true },
      { source: '/mesotherapy-for-skin', destination: '/treatments/aesthetics/medi-facials', permanent: true },
      { source: '/mesotherapy-for-skin/', destination: '/treatments/aesthetics/medi-facials', permanent: true },
      { source: '/vampire-lift-treatment', destination: '/treatments/aesthetics/vampire-lift', permanent: true },
      { source: '/vampire-lift-treatment/', destination: '/treatments/aesthetics/vampire-lift', permanent: true },
      { source: '/medi-facials-the-non-surgical-solution-for-timeless-beauty', destination: '/treatments/aesthetics/medi-facials', permanent: true },
      { source: '/medi-facials-the-non-surgical-solution-for-timeless-beauty/', destination: '/treatments/aesthetics/medi-facials', permanent: true },
      { source: '/body-perfection', destination: '/treatments/aesthetics/body-contouring', permanent: true },
      { source: '/body-perfection/', destination: '/treatments/aesthetics/body-contouring', permanent: true },
      { source: '/above-40', destination: '/treatments/aesthetics', permanent: true },
      { source: '/above-40/', destination: '/treatments/aesthetics', permanent: true },

      // Core pages
      { source: '/about-us', destination: '/about', permanent: true },
      { source: '/about-us/', destination: '/about', permanent: true },
      { source: '/contact-us', destination: '/contact', permanent: true },
      { source: '/contact-us/', destination: '/contact', permanent: true },
      { source: '/book-an-appointment', destination: '/contact', permanent: true },
      { source: '/book-an-appointment/', destination: '/contact', permanent: true },
      { source: '/departments', destination: '/treatments', permanent: true },
      { source: '/departments/', destination: '/treatments', permanent: true },

      // Blog redirects (catch-all for old blog pages)
      { source: '/blog/page/:page', destination: '/blog', permanent: true },
      { source: '/regain-your-confidence-with-gfc-hair-treatment-in-hyderabad-at-vernon-skin-clinic', destination: '/blog', permanent: true },
      { source: '/the-ultimate-guide-to-body-hair-transplant-at-vernon', destination: '/blog', permanent: true },

      // ===== Missing Service Page Redirects =====
      { source: '/muscle-relaxant-fillers-hyderabad', destination: '/treatments/aesthetics/botox-fillers', permanent: true },
      { source: '/muscle-relaxant-fillers-hyderabad/', destination: '/treatments/aesthetics/botox-fillers', permanent: true },
      { source: '/anti-dandruff-treatments', destination: '/treatments/clinical-dermatology/anti-dandruff', permanent: true },
      { source: '/anti-dandruff-treatments/', destination: '/treatments/clinical-dermatology/anti-dandruff', permanent: true },
      { source: '/medi-facial', destination: '/treatments/aesthetics/medi-facials', permanent: true },
      { source: '/medi-facial/', destination: '/treatments/aesthetics/medi-facials', permanent: true },
      { source: '/insta-glow-facial', destination: '/treatments/aesthetics/medi-facials', permanent: true },
      { source: '/insta-glow-facial/', destination: '/treatments/aesthetics/medi-facials', permanent: true },
      { source: '/glutathione-whitening-treatment', destination: '/treatments/body-wellness/glutathione-radiance', permanent: true },
      { source: '/glutathione-whitening-treatment/', destination: '/treatments/body-wellness/glutathione-radiance', permanent: true },
      { source: '/skin-brightening-system', destination: '/treatments/laser-and-pico/pico-laser-pigmentation', permanent: true },
      { source: '/skin-brightening-system/', destination: '/treatments/laser-and-pico/pico-laser-pigmentation', permanent: true },
      { source: '/men-hair-transplant', destination: '/treatments/hair-restoration/hair-transplant', permanent: true },
      { source: '/men-hair-transplant/', destination: '/treatments/hair-restoration/hair-transplant', permanent: true },
      { source: '/laser-hair-removal', destination: '/treatments/laser-and-pico/laser-hair-reduction', permanent: true },
      { source: '/laser-hair-removal/', destination: '/treatments/laser-and-pico/laser-hair-reduction', permanent: true },
      { source: '/scalp-micropigmentation', destination: '/treatments/hair-restoration/hair-transplant', permanent: true },
      { source: '/scalp-micropigmentation/', destination: '/treatments/hair-restoration/hair-transplant', permanent: true },
      { source: '/carbon-facials', destination: '/treatments/laser-and-pico/carbon-laser-peel', permanent: true },
      { source: '/carbon-facials/', destination: '/treatments/laser-and-pico/carbon-laser-peel', permanent: true },
      { source: '/bridal-and-groom-services', destination: '/treatments/body-wellness/bridal-packages', permanent: true },
      { source: '/bridal-and-groom-services/', destination: '/treatments/body-wellness/bridal-packages', permanent: true },
      { source: '/model-movie-star-aspirant', destination: '/treatments/aesthetics', permanent: true },
      { source: '/model-movie-star-aspirant/', destination: '/treatments/aesthetics', permanent: true },

      // ===== Missing Core Page Redirects =====
      { source: '/dermatologist', destination: '/about/dr-brahmananda-reddy', permanent: true },
      { source: '/dermatologist/', destination: '/about/dr-brahmananda-reddy', permanent: true },
      { source: '/doctor', destination: '/about/our-team', permanent: true },
      { source: '/doctor/', destination: '/about/our-team', permanent: true },
      { source: '/doctor/:slug', destination: '/about/our-team', permanent: true },
      { source: '/career', destination: '/contact', permanent: true },
      { source: '/career/', destination: '/contact', permanent: true },
      { source: '/job-application', destination: '/contact', permanent: true },
      { source: '/job-application/', destination: '/contact', permanent: true },
      { source: '/terms-conditions', destination: '/terms', permanent: true },
      { source: '/terms-conditions/', destination: '/terms', permanent: true },
      { source: '/privacy-policy', destination: '/privacy', permanent: true },
      { source: '/privacy-policy/', destination: '/privacy', permanent: true },
      { source: '/contact-clinic', destination: '/contact', permanent: true },
      { source: '/contact-clinic/', destination: '/contact', permanent: true },
      { source: '/contact-counsellor', destination: '/contact', permanent: true },
      { source: '/contact-counsellor/', destination: '/contact', permanent: true },
      { source: '/counsellor', destination: '/contact', permanent: true },
      { source: '/counsellor/', destination: '/contact', permanent: true },
      { source: '/clinic', destination: '/locations', permanent: true },
      { source: '/clinic/', destination: '/locations', permanent: true },
      { source: '/covid-19', destination: '/', permanent: true },
      { source: '/covid-19/', destination: '/', permanent: true },
      { source: '/homep', destination: '/', permanent: true },
      { source: '/homep/', destination: '/', permanent: true },
      { source: '/landing-page', destination: '/', permanent: true },
      { source: '/landing-page/', destination: '/', permanent: true },
      { source: '/home-page-one', destination: '/', permanent: true },
      { source: '/home-page-one/', destination: '/', permanent: true },
      { source: '/book-an-appointment-2', destination: '/contact', permanent: true },
      { source: '/book-an-appointment-2/', destination: '/contact', permanent: true },

      // ===== Blog Post Redirects (all old root-level posts → /blog) =====
      { source: '/the-ultimate-guide-to-hair-restoration-regrowth', destination: '/blog', permanent: true },
      { source: '/the-ultimate-guide-to-hair-restoration-regrowth/', destination: '/blog', permanent: true },
      { source: '/say-goodbye-to-dull-skin-try-a-medi-facial-today', destination: '/blog', permanent: true },
      { source: '/say-goodbye-to-dull-skin-try-a-medi-facial-today/', destination: '/blog', permanent: true },
      { source: '/bride-groom-skin-lightening-treatment', destination: '/blog', permanent: true },
      { source: '/bride-groom-skin-lightening-treatment/', destination: '/blog', permanent: true },
      { source: '/the-ultimate-derma-peels-skin-treatments', destination: '/blog', permanent: true },
      { source: '/the-ultimate-derma-peels-skin-treatments/', destination: '/blog', permanent: true },
      { source: '/tropical-steroids-treatment-in-anti-dandruff-care', destination: '/blog', permanent: true },
      { source: '/tropical-steroids-treatment-in-anti-dandruff-care/', destination: '/blog', permanent: true },
      { source: '/your-guide-to-fuller-brows-eyebrow-hair-transplants', destination: '/blog', permanent: true },
      { source: '/your-guide-to-fuller-brows-eyebrow-hair-transplants/', destination: '/blog', permanent: true },
      { source: '/mesotherapy-for-skin-treatment', destination: '/blog', permanent: true },
      { source: '/mesotherapy-for-skin-treatment/', destination: '/blog', permanent: true },
      { source: '/medi-facials-the-non-surgical-solution-for-timeless-beauty', destination: '/blog', permanent: true },
      { source: '/muscle-relaxant-filler-treatment', destination: '/blog', permanent: true },
      { source: '/muscle-relaxant-filler-treatment/', destination: '/blog', permanent: true },
      { source: '/unlock-radiant-skin-with-glutathione-whitening-treatment', destination: '/blog', permanent: true },
      { source: '/unlock-radiant-skin-with-glutathione-whitening-treatment/', destination: '/blog', permanent: true },
      { source: '/transform-your-look-with-mega-and-giga-hair-transplant-sessions', destination: '/blog', permanent: true },
      { source: '/transform-your-look-with-mega-and-giga-hair-transplant-sessions/', destination: '/blog', permanent: true },
      { source: '/revitalize-your-skin-with-the-carbon-facial-with-laser-treatment', destination: '/blog', permanent: true },
      { source: '/revitalize-your-skin-with-the-carbon-facial-with-laser-treatment/', destination: '/blog', permanent: true },
      { source: '/hair-transplantation-2', destination: '/blog', permanent: true },
      { source: '/hair-transplantation-2/', destination: '/blog', permanent: true },
      { source: '/10-secrets-to-crafting-the-perfect-skincare-routine-for-women', destination: '/blog', permanent: true },
      { source: '/10-secrets-to-crafting-the-perfect-skincare-routine-for-women/', destination: '/blog', permanent: true },
      { source: '/scalp-micropigmentation-in-hyderabad-achieve-a-fuller-hairline-at-vernon-clinic', destination: '/blog', permanent: true },
      { source: '/scalp-micropigmentation-in-hyderabad-achieve-a-fuller-hairline-at-vernon-clinic/', destination: '/blog', permanent: true },
      { source: '/10-best-skin-care-home-remedies-for-glowing-skin', destination: '/blog', permanent: true },
      { source: '/10-best-skin-care-home-remedies-for-glowing-skin/', destination: '/blog', permanent: true },
      { source: '/how-to-make-the-most-of-your-monsoon-skincare-routine', destination: '/blog', permanent: true },
      { source: '/how-to-make-the-most-of-your-monsoon-skincare-routine/', destination: '/blog', permanent: true },
      { source: '/what-is-micropigmentation', destination: '/blog', permanent: true },
      { source: '/what-is-micropigmentation/', destination: '/blog', permanent: true },
      { source: '/treatment-options-for-facial-scarring', destination: '/blog', permanent: true },
      { source: '/treatment-options-for-facial-scarring/', destination: '/blog', permanent: true },
      { source: '/what-is-scalp-micropigmentation', destination: '/blog', permanent: true },
      { source: '/what-is-scalp-micropigmentation/', destination: '/blog', permanent: true },
      { source: '/natural-acne-treatment', destination: '/blog', permanent: true },
      { source: '/natural-acne-treatment/', destination: '/blog', permanent: true },
      { source: '/is-blue-light-harming-your-skin-health', destination: '/blog', permanent: true },
      { source: '/is-blue-light-harming-your-skin-health/', destination: '/blog', permanent: true },
      { source: '/cicatrization', destination: '/blog', permanent: true },
      { source: '/cicatrization/', destination: '/blog', permanent: true },
      { source: '/carbon-facial', destination: '/blog', permanent: true },
      { source: '/carbon-facial/', destination: '/blog', permanent: true },
      { source: '/its-skin-brightening-system', destination: '/blog', permanent: true },
      { source: '/its-skin-brightening-system/', destination: '/blog', permanent: true },
      { source: '/medi-facial-vs-hydrafacial-which-is-right-for-you', destination: '/blog', permanent: true },
      { source: '/medi-facial-vs-hydrafacial-which-is-right-for-you/', destination: '/blog', permanent: true },
      { source: '/10-ways-to-make-a-healthy-skin-care-routine-for-men-2', destination: '/blog', permanent: true },
      { source: '/10-ways-to-make-a-healthy-skin-care-routine-for-men-2/', destination: '/blog', permanent: true },
      { source: '/pigmentation-hair-micropigmentation', destination: '/blog', permanent: true },
      { source: '/pigmentation-hair-micropigmentation/', destination: '/blog', permanent: true },
      { source: '/vernon-facial-aesthetics', destination: '/blog', permanent: true },
      { source: '/vernon-facial-aesthetics/', destination: '/blog', permanent: true },
      { source: '/the-15-most-effective-acne-scar-treatments-dermatologists-swear-by', destination: '/blog', permanent: true },
      { source: '/the-15-most-effective-acne-scar-treatments-dermatologists-swear-by/', destination: '/blog', permanent: true },
      { source: '/botox-this-natural-mask-is-the-secret-to-tightening-your-skin', destination: '/blog', permanent: true },
      { source: '/botox-this-natural-mask-is-the-secret-to-tightening-your-skin/', destination: '/blog', permanent: true },
      { source: '/a-bit-about-cleansing', destination: '/blog', permanent: true },
      { source: '/a-bit-about-cleansing/', destination: '/blog', permanent: true },
      { source: '/avoid-these-diy-hacks', destination: '/blog', permanent: true },
      { source: '/avoid-these-diy-hacks/', destination: '/blog', permanent: true },
      { source: '/all-you-need-to-know-about-fue', destination: '/blog', permanent: true },
      { source: '/all-you-need-to-know-about-fue/', destination: '/blog', permanent: true },
      { source: '/bridal-glow-facials-hyderabad-shine-on-your-wedding-day-at-vernon-clinic', destination: '/blog', permanent: true },
      { source: '/bridal-glow-facials-hyderabad-shine-on-your-wedding-day-at-vernon-clinic/', destination: '/blog', permanent: true },
      { source: '/what-is-niacinamide-use-side-effects-health-benefits-and-usage-of-niacinamide', destination: '/blog', permanent: true },
      { source: '/what-is-niacinamide-use-side-effects-health-benefits-and-usage-of-niacinamide/', destination: '/blog', permanent: true },
      { source: '/skin-beauty', destination: '/blog', permanent: true },
      { source: '/skin-beauty/', destination: '/blog', permanent: true },
      { source: '/how-to-build-a-skin-care-routine', destination: '/blog', permanent: true },
      { source: '/how-to-build-a-skin-care-routine/', destination: '/blog', permanent: true },
      { source: '/achieve-flawless-skin-with-q-switch-laser-treatment-in-hyderabad-at-vernon-clinic', destination: '/blog', permanent: true },
      { source: '/achieve-flawless-skin-with-q-switch-laser-treatment-in-hyderabad-at-vernon-clinic/', destination: '/blog', permanent: true },
      { source: '/a-bit-about-hair-transplantation', destination: '/blog', permanent: true },
      { source: '/a-bit-about-hair-transplantation/', destination: '/blog', permanent: true },
      { source: '/discover-the-best-hair-transplant-doctor-in-hyderabad-at-vernon-clinic-2', destination: '/blog', permanent: true },
      { source: '/discover-the-best-hair-transplant-doctor-in-hyderabad-at-vernon-clinic-2/', destination: '/blog', permanent: true },
      { source: '/botox-vs-fillers-unveiling-the-secrets-to-a-youthful-you', destination: '/blog', permanent: true },
      { source: '/botox-vs-fillers-unveiling-the-secrets-to-a-youthful-you/', destination: '/blog', permanent: true },
      { source: '/female-beard-more-than-an-aesthetic-issue-it-can-be-a-symptom-of-a-disease', destination: '/blog', permanent: true },
      { source: '/female-beard-more-than-an-aesthetic-issue-it-can-be-a-symptom-of-a-disease/', destination: '/blog', permanent: true },
      { source: '/what-are-the-benefits-of-fish-oil-for-your-hair', destination: '/blog', permanent: true },
      { source: '/what-are-the-benefits-of-fish-oil-for-your-hair/', destination: '/blog', permanent: true },
      { source: '/body-oil-massage-for-smooth-skin', destination: '/blog', permanent: true },
      { source: '/body-oil-massage-for-smooth-skin/', destination: '/blog', permanent: true },
      { source: '/the-vitamin-c-line-from-pfc-cosmetics', destination: '/blog', permanent: true },
      { source: '/the-vitamin-c-line-from-pfc-cosmetics/', destination: '/blog', permanent: true },
      { source: '/all-about-beard-transplant', destination: '/blog', permanent: true },
      { source: '/all-about-beard-transplant/', destination: '/blog', permanent: true },
      { source: '/do-you-know-how-blue-light-and-what-those-hours-in-front-of-the-screen-do-to-your-skin', destination: '/blog', permanent: true },
      { source: '/do-you-know-how-blue-light-and-what-those-hours-in-front-of-the-screen-do-to-your-skin/', destination: '/blog', permanent: true },
      { source: '/hide-your-baldness-permanently-in-60-minutes', destination: '/blog', permanent: true },
      { source: '/hide-your-baldness-permanently-in-60-minutes/', destination: '/blog', permanent: true },
      { source: '/how-is-a-hair-transplant-performed', destination: '/blog', permanent: true },
      { source: '/how-is-a-hair-transplant-performed/', destination: '/blog', permanent: true },
      { source: '/how-stress-effects-the-skin', destination: '/blog', permanent: true },
      { source: '/how-stress-effects-the-skin/', destination: '/blog', permanent: true },
      { source: '/hair-transplant', destination: '/blog', permanent: true },
      { source: '/hair-transplant/', destination: '/blog', permanent: true },
      { source: '/pigments-on-face', destination: '/blog', permanent: true },
      { source: '/pigments-on-face/', destination: '/blog', permanent: true },
      { source: '/vitamins-for-a-healthy-heart', destination: '/blog', permanent: true },
      { source: '/vitamins-for-a-healthy-heart/', destination: '/blog', permanent: true },
      { source: '/sw', destination: '/', permanent: true },
      { source: '/sw/', destination: '/', permanent: true },
      { source: '/elementor-52490', destination: '/', permanent: true },
      { source: '/elementor-52490/', destination: '/', permanent: true },

      // ===== WordPress artifact redirects =====
      { source: '/wp-content/:path*', destination: '/', permanent: true },
      { source: '/wp-admin', destination: '/', permanent: true },
      { source: '/wp-login.php', destination: '/', permanent: true },
      { source: '/feed', destination: '/', permanent: true },
      { source: '/feed/', destination: '/', permanent: true },
      { source: '/mp-event/:path*', destination: '/', permanent: true },
      { source: '/mega_menu/:path*', destination: '/', permanent: true },

      // Phonetic confusion searches
      { source: '/werner-skin-clinic', destination: '/', permanent: true },
      { source: '/vernon-skinner', destination: '/', permanent: true },
    ]
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          {
            key: 'X-Frame-Options',
            value: 'DENY',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin',
          },
        ],
      },
    ]
  },
}

export default nextConfig
